# Generated by Django 3.2 on 2023-09-02 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230902_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoplato',
            name='pedido_id',
            field=models.ForeignKey(db_column='pedido_id', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='pedidoplatos', to='api.pedido'),
        ),
    ]
